
name: Get latest release version

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  update-latest-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch latest releases
      run: |
        curl -sS https://api.github.com/repos/infinityworks/prometheus-rancher-exporter/releases/latest | jq -r '{name, tag_name, body}' > releases/latest.json
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update latest release
