name: Build and publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: infinityworks/prometheus-rancher-exporter
        ref: master

    - name: Generate build files
      uses: thatisuday/go-cross-build@v1
      with:
          platforms: 'linux/amd64'
          package: ''
          name: 'rancher_exporter'
          compress: 'true'
          dest: 'dist'

    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: dist/rancher_exporter-linux-amd64.tar.gz
        release: v0.24.0-alpha
        message: This is a pre-release from the infinityworks/prometheus-rancher-exporter master branch.
